max_seq_len: 2048
global_seed: 19950815

# Run Name
run_name: exp03 # If left blank, will be read from env var $RUN_NAME
abci_user: # If left blank, will be read from env var $ABCI_USER

model:
  name: hf_causal_lm
  pretrained: true
  pretrained_model_name_or_path: mosaicml/mpt-30b
  init_device: mixed # 大事
  config_overrides:
    max_seq_len: ${max_seq_len}
    attn_config:
      attn_impl: torch
      # Set this to `true` if using `train_loader.dataset.packing_ratio` below
      attn_uses_sequence_id: false

# Tokenizer
tokenizer:
  name: mosaicml/mpt-30b
  kwargs:
    model_max_length: ${max_seq_len}


# Dataloaders
train_loader:
  name: finetuning
  dataset:
    hf_name: json
    hf_kwargs:
      data_dir: /scratch/${abci_user}/full
    split: train
    max_seq_len: ${max_seq_len}
    allow_pad_trimming: false
    decoder_only_format: true
    # # Use `python llmfoundry/data/packing.py --yaml-path /path/to/this/yaml/ ...`
    # # to profile this run's optimal packing_ratio as it depends on GPU count,
    # # batch size, sequence length
    # packing_ratio:
    shuffle: true
  drop_last: true
  num_workers: 8
  pin_memory: true
  prefetch_factor: 2
  persistent_workers: true
  timeout: 0

# Optimization
scheduler:
  name: linear_decay_with_warmup  # linear no warmup is HF default which dolly used
  t_warmup: 100ba  # add some warmup though, seems to help with MPT
  alpha_f: 0

optimizer:
  # Based on Dolly
  name: decoupled_lionw
  lr: 5.0e-6
  betas:
  - 0.9
  - 0.999
  eps: 1.0e-8
  weight_decay: 0

algorithms:
  gradient_clipping:
    clipping_type: norm
    clipping_threshold: 1.0

# max_duration: 2ep  # 2-3 epochs seems like the sweet spot
max_duration: 1ep
eval_interval: 1
# eval_subset_num_batches: -1
eval_first: false
global_train_batch_size: 1120 # somewhere in the 6-8 * numgpus range seems good

# System
seed: ${global_seed}
device_eval_batch_size: 1
device_train_microbatch_size: 1
precision: amp_fp16

# FSDP
fsdp_config:
  sharding_strategy: FULL_SHARD
  mixed_precision: PURE
  activation_checkpointing: true
  activation_checkpointing_reentrant: false
  activation_cpu_offload: true
  limit_all_gathers: true
  verbose: true
  state_dict_type: sharded
  sharded_ckpt_prefix_dir: ba{batch}-shards

# Logging
progress_bar: false
log_to_console: true
console_log_interval: 1ba

callbacks:
  speed_monitor:
    window_size: 10
  lr_monitor: {}
  memory_monitor: {}
  runtime_estimator: {}
  mono_ckpt_saver:
    save_folder: /scratch/${abci_user}/${run_name}/mono_checkpoints
    batch_interval: 1

# loggers:
#   wandb: {}

loggers:
  wandb:
    project: abci-llm-distributed-training-hackathon-01
    name: mpt-30b
    entity: shunk031

autoresume: true

# Checkpoint to local filesystem or remote object store
save_interval: 10ba
# save_overwrite: True
save_num_checkpoints_to_keep: 5  # Important, this cleans up checkpoints saved to DISK
save_folder: /scratch/${abci_user}/${run_name}/checkpoints
# save_folder: s3://my-bucket/my-folder/{run_name}/checkpoints
